version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net
  
  gocrud:
    build: . 
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - net
    command: "bash -c 'sleep 15 && /app/gocrud' "

  nginx:
    image: nginx
    depends_on:
      - gocrud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - net

networks:
  net:
    name: net
    driver: bridge